# Generated by Django 3.0.1 on 2019-12-25 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('current_price', models.FloatField()),
                ('open_price', models.FloatField()),
                ('previous_close', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tradder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('choice1', models.CharField(default='', max_length=90)),
                ('choice2', models.CharField(default='', max_length=90)),
                ('regular', models.CharField(default='', max_length=90)),
                ('co', models.CharField(default='', max_length=90)),
                ('amo', models.CharField(default='', max_length=90)),
                ('day', models.CharField(default='', max_length=90)),
                ('ioc', models.CharField(default='', max_length=90)),
                ('price', models.FloatField(default=True)),
                ('trigger', models.FloatField(default=True)),
                ('qty', models.IntegerField(default=True)),
                ('disclose', models.FloatField(default=True)),
                ('button', models.CharField(max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
