# Generated by Django 3.0.1 on 2019-12-25 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradder',
            name='updated_at',
        ),
    ]
