# Generated by Django 3.0.1 on 2019-12-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0002_remove_tradder_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradder',
            name='field_name',
            field=models.TimeField(auto_now=True),
        ),
    ]
