# Generated by Django 3.0.1 on 2019-12-25 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0004_auto_20191225_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradder',
            name='amo',
        ),
        migrations.RemoveField(
            model_name='tradder',
            name='co',
        ),
        migrations.RemoveField(
            model_name='tradder',
            name='day',
        ),
        migrations.RemoveField(
            model_name='tradder',
            name='ioc',
        ),
    ]
